# Generated by Django 5.2.5 on 2025-09-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('password', models.TextField(max_length=16)),
            ],
            options={
                'db_table': 'firstdjango',
                'ordering': ['user'],
            },
        ),
    ]
