# Generated by Django 5.2.5 on 2025-09-20 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evreyting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='students',
            table='users',
        ),
    ]
