# Generated by Django 5.2.5 on 2025-09-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evreyting', '0002_alter_students_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='students',
            name='user',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
