# Generated by Django 5.2.5 on 2025-09-22 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evreyting', '0003_alter_students_email_alter_students_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=2)),
                ('points', models.IntegerField()),
            ],
            options={
                'db_table': 'customers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItemNotes',
            fields=[
                ('note_id', models.IntegerField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(db_column='order_Id')),
                ('product_id', models.IntegerField()),
                ('note', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'order_item_notes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('pk', models.CompositePrimaryKey('order_id', 'product_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'db_table': 'order_items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateField()),
                ('comments', models.CharField(blank=True, max_length=2000, null=True)),
                ('shipped_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderStatuses',
            fields=[
                ('order_status_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'order_statuses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('quantity_in_stock', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Shippers',
            fields=[
                ('shipper_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'shippers',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
