# Generated by Django 5.2.5 on 2025-10-02 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evreyting', '0004_customers_orderitemnotes_orderitems_orders_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(null=True, upload_to='images/')),
                ('uploaded_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Customers',
        ),
        migrations.DeleteModel(
            name='OrderItemNotes',
        ),
        migrations.DeleteModel(
            name='OrderItems',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
        migrations.DeleteModel(
            name='OrderStatuses',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.DeleteModel(
            name='Shippers',
        ),
    ]
