# Generated by Django 5.2.5 on 2025-10-02 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evreyting', '0005_photos_delete_customers_delete_orderitemnotes_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photos',
            new_name='Images',
        ),
    ]
