# Generated by Django 5.2.5 on 2025-10-02 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evreyting', '0006_rename_photos_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='photo',
            field=models.ImageField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='images',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
