# Generated by Django 5.2.5 on 2025-10-09 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evreyting', '0007_alter_images_photo_alter_images_uploaded_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
